import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[window]
padding = { x = 15, y = 5 }

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Never" }

[scrolling]
history = 100000

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Control"

[font]
size = 12.0
[font.normal]
family = "Monaspace Neon"
style = "Regular"
[font.italic]
family = "Monaspace Neon"
style = "Italic"
[font.bold]
family = "Monaspace Krypton"
style = "Bold"
